### ISSUE TITLE
S'pht Happens misaligned door textures

### ISSUE THREAD

**Issue by Pfhorrest** [Pfhorrest/Eternal#130]
Teleport to them to fix them without opening them.

Probably all doors that open only once need fixing, but at least these ones definitely do...
![Screen Shot 2020-02-29 at 12 53 50 AM](https://user-images.githubusercontent.com/5233345/75604935-bbc20080-5a92-11ea-9a14-f4f24118e0c3.png)
![Screen Shot 2020-02-29 at 12 50 10 AM](https://user-images.githubusercontent.com/5233345/75604936-bd8bc400-5a92-11ea-9f21-34c9ac932633.png)
![Screen Shot 2020-02-29 at 1 02 41 AM](https://user-images.githubusercontent.com/5233345/75604938-bf558780-5a92-11ea-8c01-848be16bc1a5.png)
![Screen Shot 2020-02-29 at 12 56 47 AM](https://user-images.githubusercontent.com/5233345/75604940-c11f4b00-5a92-11ea-8197-1d67787887da.png)

**Comment by Pfhorrest** [comment]
how do these need fixing again (can we just write a script to fix all of these?)

![Screen Shot 2020-04-03 at 12 34 18 AM](https://user-images.githubusercontent.com/5233345/78343956-7a6cb700-7550-11ea-92cc-b85a92682cdf.png)
![Screen Shot 2020-04-03 at 12 37 31 AM](https://user-images.githubusercontent.com/5233345/78343968-7e98d480-7550-11ea-925b-c01683038bf0.png)
![Screen Shot 2020-04-03 at 12 38 16 AM](https://user-images.githubusercontent.com/5233345/78343980-835d8880-7550-11ea-9c80-b2caa6759acf.png)

**Comment by aaronfreed** [comment]
i think i got them all

[S'pht Happens.zip](https://github.com/Pfhorrest/Eternal/files/4486008/S.pht.Happens.zip)
