### ISSUE TITLE
S'pht Happens misaligned texture

### ISSUE THREAD

**Issue by Pfhorrest** [Pfhorrest/Eternal#131]
![Screen Shot 2020-02-29 at 1 01 27 AM](https://user-images.githubusercontent.com/5233345/75604952-ddbb8300-5a92-11ea-82fd-de7221c03c6a.png)

**Comment by Pfhorrest** [comment]
somehow this got un-fixed and now needs to be fixed again

**Comment by aaronfreed** [comment]
[S'pht Happens.zip](https://github.com/Pfhorrest/Eternal/files/4486008/S.pht.Happens.zip)
