### ISSUE TITLE
S'pht Happens charger should stay active

### ISSUE THREAD

**Issue by Pfhorrest** [Pfhorrest/Eternal#138]
It's annoying to have it not active, and not that much easier to have it active unless someone's a cheap backtracker:

![Screen Shot 2020-03-06 at 9 41 02 PM](https://user-images.githubusercontent.com/5233345/76139135-6e014700-6002-11ea-8976-fd53fe27fad8.png)

**Comment by ravenshining** [comment]
I don't like this change, but make sure the pattern buffer and o2 terminal remain active as well if you're going this route.

**Comment by Pfhorrest** [comment]
I think I'm going to do that, and make another change that hopefully will temper this one for you. I made this change because it was really annoying to keep respawning with only 1x health in coop. So I think I'll make the elevator return to initial level, and make the bottom switch recently added deactivate by the same light currently applied to the charger etc, so that you can only get back up to that room if you respawn there in coop, but in solo you can't.
