### ISSUE TITLE
Third Rock drones not activating?

### ISSUE THREAD

**Issue by Pfhorrest** [Pfhorrest/Eternal#143]
Are the drones in the room where Aaron is here standing on monster impassible polys or something?

![Screen Shot 2020-03-06 at 10 05 59 PM](https://user-images.githubusercontent.com/5233345/76139332-963d7580-6003-11ea-92b4-95c2013116fc.png)

**Comment by Pfhorrest** [comment]
They were just blind and deaf.

**Comment by ravenshining** [comment]
Those were deliberately set to blind and deaf, both:

• Because they're supposedly hacking into those panels
• Because ones near the start would harass the player when trying to read the opening terminal
