### ISSUE TITLE
Grav blades shouldn't explode things

### ISSUE THREAD

**Issue by Pfhorrest** [Pfhorrest/Eternal#146]
Make grav blades deal fusion damage so not everything explodes when hit by them

And change weapon script to use this code so players are still immune to them when holding them:

function Triggers.player_damaged(victim, aggressor_player, aggressor_monster, damage_type, damage_amount, projectile)
    if (projectile == "shotgun bullet" or projectile == "smg bullet") and (victim.weapons.current.type == "smg" or victim.weapons.current.type == "shotgun") then
        victim.life = victim.life + damage_amount
    end
end

**Comment by ravenshining** [comment]
Note that changing the damage type to fusion will remove all "kick" from the weapon.  While this change will make it easier to harvest Fighter and Enforcer ammo, it may make it more difficult to survive fights with Hunters, as they'll explode in your face rather than at any distance.

**Comment by Pfhorrest** [comment]
Thanks for that heads-up! Kick is actually unbefitting a weapon that's supposed to be cutting straight through everything like a hot knife through butter anyway. And I'm not dead set on Hunters having hard deaths anyway, only rolling with that because both you and Aaron like it but I honestly don't.

Can you tell me what I should change so that the blades just kill things without hard deaths again like they used to?

**Comment by aaronfreed** [comment]
To change the grav blades to soft deaths:

`		<kick index="05" mult="0.03" vertical="true" death_action="6"/>
`

to:

`		<kick index="05" mult="0.03" vertical="true"/>
`

If we want to change back the WMC to trigger soft deaths as well:

`		<kick index="07" mult="0.05" vertical="true" death_action="6"/>
`

to:

`		<kick index="07" mult="0.05" vertical="true"/>
`

Be warned this will break film compatibility with previous versions whenever either of those weapons showed up. And I think things will still blow up if they’re weak to either of these weapons – so maybe hunters? If we want to undo their explosions, we’d probably have to undo their weaknesses to the WMC/grav blades. I think. 

It might be better to handle this on a map-wide basis, just by implementing a new script merged in each level to override the global settings. Then again, I suppose it also might be possible to create a plugin for 1.2.0 backwards compatibility. Maybe? I don’t know. Might be worth testing. But maybe I’m the only one that cares.

**Comment by Pfhorrest** [comment]
changed damage type to teleporter so nothing dies hard except banshees
