### ISSUE TITLE
Complete update to A Friend in Need

### ISSUE THREAD

**Issue by aaronfreed** [Pfhorrest/Eternal#161]
Implemented new precipitation plugin, overhauled map geometry, created new script that changes landscapes when player disables forcefields and excludes forcefield polygons from rain array. The bulk of this folder is changed, so I’ve just uploaded the whole thing; the only files that remain unchanged are the terminal, Rain Limits.mml, and Uniform.lua.

[12-A-Friend-In-Need.zip](https://github.com/Pfhorrest/Eternal/files/4334184/12-A-Friend-In-Need.zip)

[see it in action here](https://youtu.be/fQ8f-P-Fqbs)

**Comment by Pfhorrest** [comment]
playtested this and found no problems, looks good
