### ISSUE TITLE
Sakhmet Rising switch is fake

### ISSUE THREAD

**Issue by Pfhorrest** [Pfhorrest/Eternal#195]
This is really just a platform or something:

![Screen Shot 2020-04-01 at 10 15 32 PM](https://user-images.githubusercontent.com/5233345/78229131-6e1b2800-7484-11ea-9b78-8a3efd55706d.png)

**Comment by aaronfreed** [comment]
Note to self: Switch at polygon 802 seems to need to be hit twice. Probably tag switch that needs to be deactivated or something.

… also, the bounciest of walls at polygon 84 and its twin. And 641, 650, 651, and 652, as long as I’m fixing those.

…i spent like an hour trying to solve the motion glitch with the wires to no avail, and it feels like my efforts have somehow just made the problem even worse; just going to raise them so the player can’t walk into those polygons and call it quits

**Comment by aaronfreed** [comment]
…here, all the stuff should at least work now. I can’t possibly spend this long obsessing over issues on the rest of these levels if we want to get the next beta out anytime soon though

[Sakhmet Rising.sceA.zip](https://github.com/Pfhorrest/Eternal/files/4436070/Sakhmet.Rising.sceA.zip)
