### ISSUE TITLE
Heart of Fusion mistextured split door

### ISSUE THREAD

**Issue by Pfhorrest** [Pfhorrest/Eternal#197]
Thanks Vasara:

![Screen Shot 2020-04-01 at 11 06 13 PM](https://user-images.githubusercontent.com/5233345/78229296-a6bb0180-7484-11ea-8bfa-69a28fddff65.png)

**Comment by aaronfreed** [comment]
fixed, along with a few other things:

[Heart-of-Fusion.sceA.zip](https://github.com/Pfhorrest/Eternal/files/4442050/Heart-of-Fusion.sceA.zip)

(replaced with newer link 2020/04/07)
