### ISSUE TITLE
Killing the Giants weird goo blobs

### ISSUE THREAD

**Issue by Pfhorrest** [Pfhorrest/Eternal#201]
These glowing goo things outside the ship should have some other texture instead:

![Screen Shot 2020-04-02 at 12 05 08 AM](https://user-images.githubusercontent.com/5233345/78229689-2fd23880-7485-11ea-9c05-ea7f532821bd.png)

**Comment by aaronfreed** [comment]
Fixed. https://github.com/Pfhorrest/Eternal/issues/221
