### ISSUE TITLE
My Kingdom Pfhor A Horse bouncy polygons

### ISSUE THREAD

**Issue by Pfhorrest** [Pfhorrest/Eternal#204]
Where Aaron (blue) is here:

![Screen Shot 2020-04-02 at 12 33 05 AM](https://user-images.githubusercontent.com/5233345/78229943-863f7700-7485-11ea-9510-8958a5153a2d.png)

**Comment by aaronfreed** [comment]
[My-Kingdom-Pfhor-A-Horse.sceA.zip](https://github.com/Pfhorrest/Eternal/files/4464225/My-Kingdom-Pfhor-A-Horse.sceA.zip)

There were a bunch of others too. All should be fixed now. Made a few other cosmetic changes here and there – the goo now makes sounds; you can hear the rain at the edge of the ship; stuff like that. (Also, when you activate tag three to open the end of the level, another door – 316 on this revision – now opens)
