### ISSUE TITLE
Pissing On / Burning Down The Corporation bouncy polygons

### ISSUE THREAD

**Issue by Pfhorrest** [Pfhorrest/Eternal#205]
![Screen Shot 2020-04-02 at 12 41 24 AM](https://user-images.githubusercontent.com/5233345/78230014-a111eb80-7485-11ea-9034-ac78b3c4b9be.png)

**Comment by aaronfreed** [comment]
Fixed most of these issues; just not sure how to fix the “stuck compiler” thing. (Might just have to make all those walls solid.) On the other hand, there was also an issue with a S’pht’Kr getting stuck on the northwestern circular platform and screwing up its timing; I simply raised the ceiling of that by 1 WU to eliminate the problem. Also added a bit of fusion ammo to the areas with the drones in each of these levels, to give the player a reward for exploring those areas. The one in “Burning” is a secret anyway so it really doesn’t matter whether the ammo makes story sense.

[Pissing-on-the-Corporation.sceA.zip](https://github.com/Pfhorrest/Eternal/files/4464357/Pissing-on-the-Corporation.sceA.zip)

[Burning-Down-The-Corporation.sceA.zip](https://github.com/Pfhorrest/Eternal/files/4464356/Burning-Down-The-Corporation.sceA.zip)
