### ISSUE TITLE
S'pht'ia terminal mishap

### ISSUE THREAD

**Issue by Pfhorrest** [Pfhorrest/Eternal#207]
This should have its header all on one line (check for similar errors):

![Screen Shot 2020-04-02 at 11 59 22 PM](https://user-images.githubusercontent.com/5233345/78343544-d420b180-754f-11ea-9072-9e23c0f1c0e3.png)

**Comment by aaronfreed** [comment]
[Sphtia.term.txt.zip](https://github.com/Pfhorrest/Eternal/files/4486046/Sphtia.term.txt.zip)

Corrected a bunch of typos/misspellings/comma splices as well. We should double-check to make sure that this doesn’t mess up pagination now – I don’t know of any good way to preview that without actually loading up the game.
