### ISSUE TITLE
Third Rock bouncy poly

### ISSUE THREAD

**Issue by Pfhorrest** [Pfhorrest/Eternal#208]
![Screen Shot 2020-04-03 at 1 14 18 AM](https://user-images.githubusercontent.com/5233345/78343620-fa465180-754f-11ea-8cdf-a5e761464e38.png)

**Comment by aaronfreed** [comment]
[Third Rock from Lh'owon.sceA.zip](https://github.com/Pfhorrest/Eternal/files/4487050/Third.Rock.from.Lh.owon.sceA.zip)

Fixed a bunch of other bouncy polys as well, though none of the others were _this_ bouncy. Also messed around a bit with sounds and various other stuff.
