### ISSUE TITLE
Flight of Icarus misaligned door

### ISSUE THREAD

**Issue by Pfhorrest** [Pfhorrest/Eternal#209]
Can we just make a script to find and fix all of these?

![Screen Shot 2020-04-03 at 1 27 03 AM](https://user-images.githubusercontent.com/5233345/78343666-0af6c780-7550-11ea-934f-7be89235dbda.png)

**Comment by aaronfreed** [comment]
[Flight-Of-Icarus.sceA.zip](https://github.com/Pfhorrest/Eternal/files/4486578/Flight-Of-Icarus.sceA.zip)
