### ISSUE TITLE
Sleeping Gods tag switches might accidentally be on by default

### ISSUE THREAD

**Issue by Pfhorrest** [Pfhorrest/Eternal#210]
Check these:

![Screen Shot 2020-04-03 at 12 15 10 AM](https://user-images.githubusercontent.com/5233345/78343748-25c93c00-7550-11ea-941d-abde95d8dc57.png)

**Comment by aaronfreed** [comment]
Fixed. Also, they’re no longer tag switches; they’re now platform switches, and the platforms are set to activate adjacent platforms. (I used one of the longer platforms in each trio so the timing can’t get messed up.) This should prevent this from happening again, although it might not strictly comport with the original game.

Also fixed a few bouncy walls.

[Let-Sleeping-Gods-Die.sceA.zip](https://github.com/Pfhorrest/Eternal/files/4486210/Let-Sleeping-Gods-Die.sceA.zip)
