### ISSUE TITLE
S'pht Happens terminal misalignment

### ISSUE THREAD

**Issue by Pfhorrest** [Pfhorrest/Eternal#211]
The last line of this spills over onto the next page:

![Screen Shot 2020-04-03 at 12 38 54 AM](https://user-images.githubusercontent.com/5233345/78344051-a425de00-7550-11ea-9a85-b97d11c1a792.png)

**Comment by aaronfreed** [comment]
[S'pht Happens.zip](https://github.com/Pfhorrest/Eternal/files/4486008/S.pht.Happens.zip)
