### ISSUE TITLE
Eat S'pht mistextured floor

### ISSUE THREAD

**Issue by Pfhorrest** [Pfhorrest/Eternal#212]
A bit of grey amidst the brown:

![Screen Shot 2020-04-03 at 12 40 25 AM](https://user-images.githubusercontent.com/5233345/78344096-ba339e80-7550-11ea-9ad7-95874685489b.png)

**Comment by aaronfreed** [comment]
[Eat-Spht-and-Die.sceA.zip](https://github.com/Pfhorrest/Eternal/files/4486363/Eat-Spht-and-Die.sceA.zip)
