### ISSUE TITLE
Eat S'pht lava pool glitch

### ISSUE THREAD

**Issue by Pfhorrest** [Pfhorrest/Eternal#213]
The media level here should never drop below floor level (or perhaps easier, the floor should be lowered a little):

![Screen Shot 2020-04-03 at 12 41 49 AM](https://user-images.githubusercontent.com/5233345/78344196-e0593e80-7550-11ea-8451-1080e292b4cd.png)

**Comment by aaronfreed** [comment]
[Eat-Spht-and-Die.sceA.zip](https://github.com/Pfhorrest/Eternal/files/4486363/Eat-Spht-and-Die.sceA.zip)
