### ISSUE TITLE
Eat S'pht doors have wrong sounds

### ISSUE THREAD

**Issue by Pfhorrest** [Pfhorrest/Eternal#214]
These doors apparently make Pfhor door sounds:

![Screen Shot 2020-04-03 at 12 43 49 AM](https://user-images.githubusercontent.com/5233345/78344257-fc5ce000-7550-11ea-9a4c-c2869ef5dfd8.png)

**Comment by aaronfreed** [comment]
[Eat-Spht-and-Die.sceA.zip](https://github.com/Pfhorrest/Eternal/files/4486363/Eat-Spht-and-Die.sceA.zip)
