### ISSUE TITLE
Second to Last misaligned split doors

### ISSUE THREAD

**Issue by Pfhorrest** [Pfhorrest/Eternal#215]
Can we just write a script to fix all of these:

![Screen Shot 2020-04-03 at 12 55 11 AM](https://user-images.githubusercontent.com/5233345/78344331-14ccfa80-7551-11ea-9c48-6b767da0ebb5.png)

**Comment by aaronfreed** [comment]
[Second-to-Last-of-the-Mohicans.sceA.zip](https://github.com/Pfhorrest/Eternal/files/4486496/Second-to-Last-of-the-Mohicans.sceA.zip)

i’ll try to work on a script in a couple of weeks
