### ISSUE TITLE
Incredible Hulk untextured line

### ISSUE THREAD

**Issue by Pfhorrest** [Pfhorrest/Eternal#232]
![Screen Shot 2020-04-18 at 1 08 41 AM](https://user-images.githubusercontent.com/5233345/79633618-39ad9a00-811b-11ea-9b98-590e94b20300.png)

**Comment by aaronfreed** [comment]
lol, I like that you got this screenshot after I’d grenade jumped up there

I’ll have a fix for this (and other ch4 stuff) within the next day or two

**Comment by aaronfreed** [comment]
ok, the next nine days

[The-Incredible-Hulk.sceA.zip](https://github.com/Pfhorrest/Eternal/files/4541836/The-Incredible-Hulk.sceA.zip)

platform thing now fixed as well
