### ISSUE TITLE
Incredible Hulk platforms easy to get stuck behind

### ISSUE THREAD

**Issue by Pfhorrest** [Pfhorrest/Eternal#233]
This and the other one

![Screen Shot 2020-04-18 at 1 17 29 AM](https://user-images.githubusercontent.com/5233345/79633646-54800e80-811b-11ea-94e9-97110625c532.png)

**Comment by aaronfreed** [comment]
fixed, i think

[The-Incredible-Hulk.sceA.zip](https://github.com/Pfhorrest/Eternal/files/4541836/The-Incredible-Hulk.sceA.zip)
