### ISSUE TITLE
The Incredible Hulk switches behind solid lines

### ISSUE THREAD

**Issue by Pfhorrest** [Pfhorrest/Eternal#239]
This shouldn't happen:

![Screen Shot 2020-04-18 at 1 04 44 AM](https://user-images.githubusercontent.com/5233345/79633884-23540e00-811c-11ea-9bd6-857334938ea7.png)

**Comment by aaronfreed** [comment]
i think this is fixed, probably:

[The-Incredible-Hulk.sceA.zip](https://github.com/Pfhorrest/Eternal/files/4541836/The-Incredible-Hulk.sceA.zip)

we’ll want to test it, though. worst comes to worst, we’ll also have to remove those transparent textures and retexture that wall

…updated to fix that whole platform issue
