### ISSUE TITLE
This Message has a motion glitch

### ISSUE THREAD

**Issue by Pfhorrest** [Pfhorrest/Eternal#244]
![Screen Shot 2020-04-20 at 12 49 15 AM](https://user-images.githubusercontent.com/5233345/79730825-427ea700-82a6-11ea-8d33-427e33ff1094.png)

**Comment by aaronfreed** [comment]
[This-Message-Will-Self-Destruct.sceA.zip](https://github.com/Pfhorrest/Eternal/files/4550429/This-Message-Will-Self-Destruct.sceA.zip)

fixed a bunch of bouncy walls too, and a bit of screwy texturing
