### ISSUE TITLE
This Message has doors that should activate only once

### ISSUE THREAD

**Issue by Pfhorrest** [Pfhorrest/Eternal#245]
![Screen Shot 2020-04-20 at 12 57 19 AM](https://user-images.githubusercontent.com/5233345/79730887-5aeec180-82a6-11ea-88e7-0b6aaec0b8d3.png)

**Comment by Pfhorrest** [comment]
![Screen Shot 2020-04-20 at 12 58 13 AM](https://user-images.githubusercontent.com/5233345/79731196-c9cc1a80-82a6-11ea-9c32-d89f8474291c.png)

**Comment by aaronfreed** [comment]
Fix for this, but not the motion glitch – I’ll get that in the next beta (those are unpredictable and frustrating to debug).

[This-Message-Will-Self-Destruct.sceA.zip](https://github.com/Pfhorrest/Eternal/files/4541216/This-Message-Will-Self-Destruct.sceA.zip)
