### ISSUE TITLE
Where Giants Have Fallen you can see through the solid waterfall

### ISSUE THREAD

**Issue by Pfhorrest** [Pfhorrest/Eternal#247]
![Screen Shot 2020-04-20 at 1 03 22 AM](https://user-images.githubusercontent.com/5233345/79731137-b15c0000-82a6-11ea-983f-89070bd488e9.png)

**Comment by ravenshining** [comment]
That looks pretty normal to me.  If you don't want this effect, you need a thin, low polygon behind - take a look at the waterfall I put in S'pht Happens for an example.

**Comment by aaronfreed** [comment]
This may be intended behaviour for Aleph One 1.3, but it is certainly a change from older versions of the game engine, as seen in this film what I rendered with Aleph One 1.2.1 a few days ago:

https://youtu.be/13b0DvBcyaI

I suppose there’s some reasoning behind the change, but I don’t get it, honestly. It looks bad to me.

**Comment by Pfhorrest** [comment]
Since it's not clear if this is an Aleph One bug, I'm closing this issue for now.
