### ISSUE TITLE
Unwired ceiling looker

### ISSUE THREAD

**Issue by Pfhorrest** [Pfhorrest/Eternal#262]
![Screen Shot 2020-05-11 at 3 38 40 PM](https://user-images.githubusercontent.com/5233345/81629090-2e1a5f80-93b7-11ea-8e62-28456d4df030.png)

**Comment by aaronfreed** [comment]
there’s another one here 
![image](https://user-images.githubusercontent.com/8217916/83443940-97224f80-a418-11ea-8ced-003595138d1b.png)

**Comment by aaronfreed** [comment]
Both sorted.
