### ISSUE TITLE
Hysterical Womb badly sized pattern buffer

### ISSUE THREAD

**Issue by Pfhorrest** [Pfhorrest/Eternal#268]
Is there a scripty way to automatically identical all walls that are terminals, pattern buffers, switches, or chargers, and are NOT multiples of 0.5WU tall, so we can fix all of these everywhere?
![Screen Shot 2020-05-11 at 4 58 20 PM](https://user-images.githubusercontent.com/5233345/81629377-d6c8bf00-93b7-11ea-9841-0d9a520abfbc.png)

**Comment by aaronfreed** [comment]
Fixed. It's probably _possible_ to code a script to identify all of those. I'm not sure I'm capable of it _yet_ :V
