### ISSUE TITLE
Unpfhorseen misaligned texture

### ISSUE THREAD

**Issue by Pfhorrest** [Pfhorrest/Eternal#272]
The lining of that alcove shouldn't even be the same texture as the wall anyway.

![Screen Shot 2020-05-11 at 5 33 35 PM](https://user-images.githubusercontent.com/5233345/81629569-4f2f8000-93b8-11ea-8643-e3cca4a35864.png)

**Comment by aaronfreed** [comment]
![image](https://user-images.githubusercontent.com/8217916/83604237-d8fbe480-a543-11ea-9032-f09945fc4f3e.png)
texture around 3x again – i’d move them so the light is not subdivided around it

these rooms/areas, insofar as it’s even possible to fix the light textures to align with their non-light counterparts:
 
![image](https://user-images.githubusercontent.com/8217916/83604606-70613780-a544-11ea-81a9-a055e85361da.png)

![image](https://user-images.githubusercontent.com/8217916/83604680-9686d780-a544-11ea-9661-61a5a0f614f3.png)

![image](https://user-images.githubusercontent.com/8217916/83604755-ae5e5b80-a544-11ea-8b8b-286811e50b78.png)

![image](https://user-images.githubusercontent.com/8217916/83682703-4a727c00-a5b2-11ea-8b18-1544ba93255f.png)

![image](https://user-images.githubusercontent.com/8217916/83683311-2d8a7880-a5b3-11ea-8fdc-35a08cd5adc9.png)

bouncy walls:

![image](https://user-images.githubusercontent.com/8217916/83605182-786da700-a545-11ea-98cb-010f45157ec8.png)

![image](https://user-images.githubusercontent.com/8217916/83683352-41ce7580-a5b3-11ea-811d-e13675c95a0c.png)

bouncy walls all over the place in this corridor:

![image](https://user-images.githubusercontent.com/8217916/83679193-fc0eae80-a5ac-11ea-8226-e0999559926b.png)

more bounce:

![image](https://user-images.githubusercontent.com/8217916/83679887-24e37380-a5ae-11ea-81a6-67980c268314.png)

and its counterpart 180° across the room

this Enforcer starts over this goo river for no apparent reason:

![image](https://user-images.githubusercontent.com/8217916/83679645-c28a7300-a5ad-11ea-8927-bdd37d74a710.png)

do we want to hide a secret in this river?

**Comment by aaronfreed** [comment]
Done, I think
