### ISSUE TITLE
The Dead Live game-breaking switch/door

### ISSUE THREAD

**Issue by Pfhorrest** [Pfhorrest/Eternal#299]
The door controlled by this switch either needs to stop at each level, or be able to activate more than once:

![Screen Shot 2020-05-25 at 5 02 14 PM](https://user-images.githubusercontent.com/5233345/82850580-d2b99880-9eb1-11ea-9f7b-36ee1eb6644f.png)

**Comment by aaronfreed** [comment]
Fixed
