### ISSUE TITLE
These Caves have some misaligned textures

### ISSUE THREAD

**Issue by Pfhorrest** [Pfhorrest/Eternal#300]
Fixing this might require changing some walls in these tubes to a different texture, so this one doesn't wrap around 360 degrees:

![Screen Shot 2020-05-25 at 5 06 52 PM](https://user-images.githubusercontent.com/5233345/82850617-f1b82a80-9eb1-11ea-90ef-5a8c7121ae56.png)

**Comment by aaronfreed** [comment]
I remade this part of the level, so this geometry no longer even exists in this state.
