### ISSUE TITLE
These Caves have more misaligned textures

### ISSUE THREAD

**Issue by Pfhorrest** [Pfhorrest/Eternal#301]
Just re-applying the texture to this surface (and the other similar surfaces in this room) should fix it; the problem was caused by last applying the texture to the steps above it:

![Screen Shot 2020-05-25 at 5 10 41 PM](https://user-images.githubusercontent.com/5233345/82850650-190ef780-9eb2-11ea-97f3-0bcea1233c6e.png)

**Comment by aaronfreed** [comment]
Fixed when I retextured this part of the room.
