### ISSUE TITLE
Snowfrog precipitation test

### ISSUE THREAD

**Issue by aaronfreed** [Pfhorrest/Eternal#328]
Pfhorrest: Look at Snowfrog to see if it's unplayably slow on your old computer

http://simplici7y.com/items/snowfrog

**Comment by Pfhorrest** [comment]
I think ephemera makes this irrelevant? Also I no longer have that old computer easily accessible. Should I just close this?

**Comment by aaronfreed** [comment]
yeah I might as well just close it; with ephemera, it’s not really worth worrying about
