### ISSUE TITLE
Unwired elevator

### ISSUE THREAD

**Issue by Pfhorrest** [Pfhorrest/Eternal#65]
Make that hard-to-find elevator near the end of Unwired stay down when triggered so it's easier to notice, then go back up when stepped on, and come back down again if another player in coop hits the switch again.

**Comment by aaronfreed** [comment]
I have a long list of tweaks I plan to make in this level. This was one of those tweaks. I mentioned those tweaks on Discord a few weeks back and never added them here. Here they are, lightly edited for comprehensibility and to make them flow more logically:

> I want to add even more Lookers.
> 
> I’m probably going to add a few more rechargers to reduce the amount of backtracking.
> 
> I’ll try to make that platform in the southwest even less annoying (probably best to do by adding another switch closer to its actual location once it's been activated the first time).
> 
> I may add even more switches to trigger some other platforms.
> 
> Perhaps those platforms in the central area should just be activated by switches, since it's annoying to have to wait for them. The second and third platforms can just have light-dependent switches where the lights don't activate until you get to the appropriate part of the level. (I think the switches for the second and third central platforms are actually there already, so it's kind of strange that the original design didn't just use them to start with.)
> 
> Then I might also want to make it so the alarm sound effects don't actually activate until you've hit their respective switches, just to foreshadow even more heavily that the Player Should Not Be Doing This.

Some of these are pretty vague, but I remember what I meant. This is the “platform in the southwest”. I’ll probably do all this stuff in one marathon (pun more or less intended) session.

**Comment by Pfhorrest** [comment]
I fixed the elevator, but didn't make any of Aaron's changes. I'll leave it to Aaron to do those on his own time.
