### ISSUE TITLE
Terminal bugfixes on S'pht'ia

### ISSUE THREAD

**Issue by Pfhorrest** [Pfhorrest/Eternal#73]
"As many terminal as you can find" -> "As many terminals as you can find".

Also replace all double-spaces with single spaces.

**Comment by ravenshining** [comment]
Double spaces may not be in style, but they are the norm for fixed-width fonts like we have on Marathon terminals.  Certainly most of the original terminals seem to follow that convention.

**Comment by Pfhorrest** [comment]
You have a good point about typographic norms for fixed-width fonts, but pretty much all the other terminals in Eternal use single spaces, and it stood out to me when I noticed some using double spaces, so I intend to change it to uniform single spaces.
