### ISSUE TITLE
Switches on Flight of Icarus should not be mission-critical

### ISSUE THREAD

**Issue by ravenshining** [Pfhorrest/Eternal#75]
There are two switches in the room with the uplink chips.  I'm not clear on what they do, but they're apparently marked as "repair" switches.  However, the mission is to insert the uplink chips into Thoth.  The chip slots should be the only things marked repair, or the terminal should explain why you need to flip those switches.

**Comment by Pfhorrest** [comment]
Requiring those switches be active to trigger completion was important for some gameplay reason I've since forgotten, tacked on to fix an earlier bug of some sort, so I've just added a short story justification to the first terminal instead.
