### ISSUE TITLE
Hysterical Womb mission objective

### ISSUE THREAD

**Issue by Pfhorrest** [Pfhorrest/Eternal#78]
Can we make it so that you're only required to kill the controller cyborgs on Hysterical Womb? By unchecking "alien" on everything else maybe?

**Comment by ravenshining** [comment]
Unchecking alien on everything would break difficulty scaling, making this level much easier on Total Carnage and much harder on Kindergarten.

Better, we can use lua to trigger an objective once all mutants are down.

**Comment by Pfhorrest** [comment]
Apparently I didn't comment back then months ago, but I like your idea so I'm not going to do what I had planned for this, and will let you do your better plan instead, when you can.

**Comment by ravenshining** [comment]
Yeah, I read something new in the lua docs that would make this even less convoluted than I thought it would be, maybe remind me next saturday via discord or something

**Comment by Pfhorrest** [comment]
thanks raven!
