### ISSUE TITLE
Fusion cannon alt fire

### ISSUE THREAD

**Issue by Pfhorrest** [Pfhorrest/Eternal#83]
Make overcharged bolts for the Fusion Cannon either do a lot more damage or use less battery so they're not such a waste.

**Comment by Pfhorrest** [comment]
This item was created because Rampancy complained about the fusion cannon alt fire seeming useless.

But if I'm looking at the physics correctly, the alt fire can shoot four bursts of 12 shots that are each twice as damaging as one of the 48 primary fire shots, so one overcharged volley is 24 times more powerful as a single regular shot, and you get a total of twice as much damage per battery using overcharged shots than regular (at the expense of having to charge up and pick your target instead of spray and pray).

So I'm not sure anything needs to be done here, but I welcome feedback if anyone things otherwise. For now I'm closing though.

**Comment by ravenshining** [comment]
That's not how it works.  Charged shots eat ammo at 4x the rate of normal shots, you only get one shot of overcharge.  Try it for yourself and see!

Also, closing issues is not a great way of garnering feedback, I see it because I'm subscribed but by closing it you're basically hiding it from public view

**Comment by Pfhorrest** [comment]
Fixed this by changing weapon type from Dual-Function to Multipurpose.

**Comment by ravenshining** [comment]
You do realise that means one will be able to fire the primary and secondary at the same time?  Is this intended?  It might be better to change the secondary rounds/magazine, or change the damage and burst count.

**Comment by Pfhorrest** [comment]
pleas help just make it something that works i cant figure this out too much stress 

-Forrest Cameranesi, Geek of All Trades
"I am Sam. Sam I am. I do not like trolls, flames, or spam."
