### ISSUE TITLE
Stripey water transparency at lower resolutions

### ISSUE THREAD

**Issue by Pfhorrest** [Pfhorrest/Eternal#87]
Water and some other media textures have stripey transparency maps when maximum texture resolution is turned down.

**Comment by Pfhorrest** [comment]
After extensive sleuthing, it appears that some media textures (like the human sewage), when saved with no MIPmaps and no DXTC as in the 1.2 release, look fine with texture quality set to Unlimited, but stripey in different ways at lower texture quality settings.

Saving them with no MIPmaps and _with_ DXTC still works fine in Unlimited, but fails to load at all (defaulting to software) at lower texture settings.

Saving them with MIPmaps, regardless of DXTC, with any texture quality settings, isn't stripey, but is ugly in an even worse way, which is presumably why I saved them without MIPmaps (since that makes them look fine at the default Unlimited settings).

**Comment by ravenshining** [comment]
That's odd. What are you using to save your DDS files?  The presence of mipmaps shouldn't affect the full resolution image.

If you like, you could send me the unadulterated PNGs and I could convert them with the GIMP DDS plugin for you.

**Comment by ravenshining** [comment]
Here you go.  Seems to work fine for me:

[10.dds.tar.gz](https://github.com/Pfhorrest/Eternal/files/4157934/10.dds.tar.gz)

For the record the settings I used for the GIMP plugin were DXT5 compression (since you've got lots of transparent gradations going on), and repeat for the mipmap wrap mode.

**Comment by Pfhorrest** [comment]
That works great! Can you please also do all the other media textures?

Here is set1.
![10_mask](https://user-images.githubusercontent.com/5233345/73820844-808c2480-47a7-11ea-92b3-5852ce8dcd2b.png)
![10](https://user-images.githubusercontent.com/5233345/73820849-8255e800-47a7-11ea-8e63-13f22c7bef4e.png)

**Comment by Pfhorrest** [comment]
Here is set2:

![10_mask](https://user-images.githubusercontent.com/5233345/73820974-c0530c00-47a7-11ea-86b3-75a0a10e0855.png)
![10](https://user-images.githubusercontent.com/5233345/73820976-c0eba280-47a7-11ea-99e8-9d7326a706f8.png)

**Comment by Pfhorrest** [comment]
Here is set3:

![10_mask](https://user-images.githubusercontent.com/5233345/73820997-cd6ffb00-47a7-11ea-8fe7-d4f57236a00b.png)
![10](https://user-images.githubusercontent.com/5233345/73821001-cf39be80-47a7-11ea-9c64-ccf0d61c7014.png)

**Comment by Pfhorrest** [comment]
And here is set5:

![10_mask](https://user-images.githubusercontent.com/5233345/73821039-e4aee880-47a7-11ea-90b7-93764157a448.png)
![10](https://user-images.githubusercontent.com/5233345/73821044-e9739c80-47a7-11ea-800f-77c69df8b092.png)

**Comment by Pfhorrest** [comment]
Can you also please do versions of all of those downscaled to 1024x1024 and 512x512 when you have the chance, as downscaling all the /0Special textures to try fixing the Windows out-of-memory errors is going to be my next thing.

**Comment by Pfhorrest** [comment]
per Discord chat, here are the window textures too for the same treatment, one set at a time. Set1:

![08_mask](https://user-images.githubusercontent.com/5233345/73821451-dad9b500-47a8-11ea-9f37-1b312debc68a.png)
![08](https://user-images.githubusercontent.com/5233345/73821457-db724b80-47a8-11ea-8983-386545212294.png)

**Comment by Pfhorrest** [comment]
set2:

![08_mask](https://user-images.githubusercontent.com/5233345/73821483-e88f3a80-47a8-11ea-8665-1baf17af6d4e.png)
![08](https://user-images.githubusercontent.com/5233345/73821485-e927d100-47a8-11ea-8721-39d08668fb10.png)

**Comment by Pfhorrest** [comment]
set3:

![08_mask](https://user-images.githubusercontent.com/5233345/73821518-f644c000-47a8-11ea-92d1-9a861e897d10.png)
![08](https://user-images.githubusercontent.com/5233345/73821519-f6dd5680-47a8-11ea-8b8d-e7c1ad520957.png)

**Comment by Pfhorrest** [comment]
set4:

![08_mask](https://user-images.githubusercontent.com/5233345/73821540-00ff5500-47a9-11ea-8a41-9abd34df5e7f.png)
![08](https://user-images.githubusercontent.com/5233345/73821542-00ff5500-47a9-11ea-80df-10f8d73c1518.png)

**Comment by Pfhorrest** [comment]
set5:

![08_mask](https://user-images.githubusercontent.com/5233345/73821570-0ceb1700-47a9-11ea-9267-45557243a41c.png)
![08](https://user-images.githubusercontent.com/5233345/73821572-0d83ad80-47a9-11ea-8b70-ca75539561f8.png)

**Comment by Pfhorrest** [comment]
And if you can do those in 1024x1024 and 512x512 too that'd be great!

**Comment by Pfhorrest** [comment]
Thanks Raven for taking care of all of these.

**Comment by Pfhorrest** [comment]
For completeness going forward here is also the set 4 media images:

![10_mask](https://user-images.githubusercontent.com/5233345/76657796-e8185b00-652f-11ea-8945-565cf29980da.png)

![10_mask](https://user-images.githubusercontent.com/5233345/76657800-e9e21e80-652f-11ea-824e-7edf1bf99a5d.png)

**Comment by Pfhorrest** [comment]
I had to manually resave everything at 1024 with Aorta, so now everything looks shitty when using MIP map settings again:

![Screen Shot 2020-03-14 at 12 49 18 AM](https://user-images.githubusercontent.com/5233345/76677723-02cdec80-658f-11ea-9524-aaaea7d88b44.png)
![Screen Shot 2020-03-14 at 12 48 11 AM](https://user-images.githubusercontent.com/5233345/76677726-082b3700-658f-11ea-92ac-6b6eae234ad1.png)
![Screen Shot 2020-03-14 at 12 45 41 AM](https://user-images.githubusercontent.com/5233345/76677727-09f4fa80-658f-11ea-9605-69731b0f52e5.png)
![Screen Shot 2020-03-14 at 12 44 59 AM](https://user-images.githubusercontent.com/5233345/76677728-0bbebe00-658f-11ea-8d19-4c7ad45d8394.png)
![Screen Shot 2020-03-14 at 12 52 10 AM](https://user-images.githubusercontent.com/5233345/76677762-4294d400-658f-11ea-8211-553402becba6.png)

**Comment by aaronfreed** [comment]
Forgeflow is working on these now. The first one he sent didn’t have any issues:

[water.zip](https://github.com/Pfhorrest/Eternal/files/4338662/water.zip)

No striping or anything when I load it at a lower resolution (though this was on Mac and I think most of the people who were having issues were on Windows; I’ll test on Windows as well when I’m not rendering films).

I’ll add the rest here when they come in.

…The rest of the liquids:

[Eternal_Liquids.zip](https://github.com/Pfhorrest/Eternal/files/4338713/Eternal_Liquids.zip)

**Comment by Pfhorrest** [comment]
The source of this problem appears to be the fast halo removal option in Aorta. Correct settings to use should be: DXTC, MIPmaps, no fast halo removal or edge color correction.

**Comment by Pfhorrest** [comment]
Hurray, it works.

For future reference, window textures with big white/black areas that are supposed to be transparent need DXTC off (on both the original and the bump map) or else they get filled with weird subtle large pixels.
