### ISSUE TITLE
Recolor all textures

### ISSUE THREAD

**Issue by Pfhorrest** [Pfhorrest/Eternal#94]
I've been thinking that Eternal should have had the Marathon set with orange-centered hues and the Lh'owon set with green-centered hues, since Lh'owon events took place before its desertification and the original Marathon textures weren't so green as mine, with more browns and such. Also the "Jjaro" (chapter 4) set should have been azure-centric to fit better with the ice-planet theme, and the "Forerunner" (chapter 5) set should have been the one with a neutral color balance.

In the Marathon set, all the greens would become yellow-browns, the current yellow-browns would become orange-browns, the magentas would become red-browns, and the cyans would become azures.

In the Lh'owon set, all the yellows would become greens, all the oranges would become yellows, all the reds would become magentas, and the azures would become cyans

In the Jjaro set, orange and azure would remain unchanged, but green would become cyan and magenta would become blue.

In the Forerunner set, azure and orange would remain the same, but cyans would become greens and blues would become magentas.

**Comment by Pfhorrest** [comment]
I did the new graphics, Aaron has them and will implement them.

**Comment by aaronfreed** [comment]
Done. Looks amazing. Great job.
