### ISSUE TITLE
Check all new terminal pics

### ISSUE THREAD

**Issue by Pfhorrest** [Pfhorrest/Eternal#95]
Double-check all terminal pics that I didn't create, make sure they conform correctly to the standard Illustrator templates, correct them if they don't.

**Comment by Pfhorrest** [comment]
Raven if you have the source images used in images 1002 and 01203 I'd appreciate them, or better still the (I presume) XCF files you made out of them. I'm recreating source art for all the term picts you created so that we don't just have the merged JPEGs, and may be re-saving them through Illustrator to avoid slight stylistic differences created between that and GIMP.

**Comment by Pfhorrest** [comment]
There are now folders in /Eternal/Resources-source/PICT/Eternal term picts/Specific for all those images (with 0 prepended to the filenames for the prologue, for consistency) so you can just upload them there if you like.

**Comment by Pfhorrest** [comment]
I managed to make do without those.

**Comment by ravenshining** [comment]
Sorry I'm late to the party, but I did track down the original editied sshots prior to adding the filter:

Under the spoiler here:
http://pfhorums.com/viewtopic.php?p=186081#p186081

And from Discord:
https://cdn.discordapp.com/attachments/430075740889808908/522674129791614978/Sphtia_0014.jpg
